// <auto-generated />
using System;
using CursoIdiomas.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CursoIdiomas.Infra.Data.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20210923014210_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CursoIdiomas.Domain.Entities.Curso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CargaHoraria")
                        .HasColumnType("int");

                    b.Property<int>("Dificuldade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Curso");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f52f2fea-d24b-4dfb-b278-f2e973bc8b47"),
                            CargaHoraria = 70,
                            Dificuldade = 1,
                            Nome = "Inglês"
                        },
                        new
                        {
                            Id = new Guid("3a954806-e673-408e-9a6e-b8bb859ea810"),
                            CargaHoraria = 70,
                            Dificuldade = 1,
                            Nome = "Espanhol"
                        },
                        new
                        {
                            Id = new Guid("bea6a055-e757-41fd-a69e-c7783719cf12"),
                            CargaHoraria = 80,
                            Dificuldade = 1,
                            Nome = "Italiano"
                        },
                        new
                        {
                            Id = new Guid("cb1c6fe0-5490-4da3-bb9a-a7986ca10e55"),
                            CargaHoraria = 90,
                            Dificuldade = 1,
                            Nome = "Alemão"
                        },
                        new
                        {
                            Id = new Guid("82e2c700-607b-43ba-bde3-af6d86bd582c"),
                            CargaHoraria = 110,
                            Dificuldade = 2,
                            Nome = "Inglês"
                        },
                        new
                        {
                            Id = new Guid("9a66c62a-c854-4617-9141-c0fc838da6ae"),
                            CargaHoraria = 110,
                            Dificuldade = 2,
                            Nome = "Espanhol"
                        },
                        new
                        {
                            Id = new Guid("2ca6aaad-0dec-4326-b7fa-4dcf985f3fab"),
                            CargaHoraria = 150,
                            Dificuldade = 2,
                            Nome = "Italiano"
                        },
                        new
                        {
                            Id = new Guid("b03a7f95-1433-4b90-b1e6-7f9d45972ed0"),
                            CargaHoraria = 180,
                            Dificuldade = 2,
                            Nome = "Alemão"
                        },
                        new
                        {
                            Id = new Guid("4e0a9aca-57b6-44eb-9868-15d23a44fbdd"),
                            CargaHoraria = 150,
                            Dificuldade = 3,
                            Nome = "Inglês"
                        },
                        new
                        {
                            Id = new Guid("9d9968a2-5055-4210-b531-8ec51321f7cb"),
                            CargaHoraria = 190,
                            Dificuldade = 3,
                            Nome = "Espanhol"
                        },
                        new
                        {
                            Id = new Guid("7e3140e5-82a1-44ff-9f59-b1402eea0878"),
                            CargaHoraria = 220,
                            Dificuldade = 3,
                            Nome = "Italiano"
                        },
                        new
                        {
                            Id = new Guid("e79e6343-c99a-46c5-afaa-e8dd180561ef"),
                            CargaHoraria = 280,
                            Dificuldade = 3,
                            Nome = "Alemão"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
